language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

sudo: false

env:
  - NODE_ENV=test

after_success:
  - 'if [ "${TRAVIS_NODE_VERSION}" = "node" ] ; then make publish-coverage ; fi'