language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"

sudo: false

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules

after_success:
  - npm install codeclimate-test-reporter
  - npm run test-travis
  - codeclimate-test-reporter < coverage/lcov.info

matrix:
  fast_finish: true
