language: node_js

node_js:
  - "node"
  - "6"
  - "5"
  - "4"
  - "0.12"
  - "0.10"

matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.12"
    - node_js: "0.10"

sudo: false

env:
  - NODE_ENV=test

after_success:
  - make publish-coverage