language: node_js

node_js:
  - "0.10"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"

sudo: false

env:
  - NODE_ENV=test

cache:
  directories:
    - node_modules

matrix:
  fast_finish: true
  include:
    - node_js: "0.10"
      env: COVERAGE=true
  allow_failures:
    - node_js: "0.10"
      env: COVERAGE=true
